// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDosXiNDCeT1JnSc7A1QTb41MZf4p-2QIY',
    appId: '1:230038428073:web:30d6afcd934643b30c8cb8',
    messagingSenderId: '230038428073',
    projectId: 'tiendamascotas-f8f57',
    authDomain: 'tiendamascotas-f8f57.firebaseapp.com',
    storageBucket: 'tiendamascotas-f8f57.appspot.com',
    measurementId: 'G-8PBS7JWGJC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZTSWvKtM8cNn7T7FmQ9yhy7IXpC6voT4',
    appId: '1:230038428073:android:c8b862d99383be4c0c8cb8',
    messagingSenderId: '230038428073',
    projectId: 'tiendamascotas-f8f57',
    storageBucket: 'tiendamascotas-f8f57.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARNn0Cz1qAldoLaDvcrQGwlv2ybsnCOYs',
    appId: '1:230038428073:ios:8b16298ce945313d0c8cb8',
    messagingSenderId: '230038428073',
    projectId: 'tiendamascotas-f8f57',
    storageBucket: 'tiendamascotas-f8f57.appspot.com',
    iosClientId: '230038428073-ofkddkvug9hnj6uumv72q35dkrbrd4ba.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiendaMascotas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARNn0Cz1qAldoLaDvcrQGwlv2ybsnCOYs',
    appId: '1:230038428073:ios:d4e5d604d1965b050c8cb8',
    messagingSenderId: '230038428073',
    projectId: 'tiendamascotas-f8f57',
    storageBucket: 'tiendamascotas-f8f57.appspot.com',
    iosClientId: '230038428073-h41m0stmqqbmetls4sa7r6dll7dug52p.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiendaMascotas.RunnerTests',
  );
}
